"""phase 2 core PI domain and AI outputs

Revision ID: 0003_core_pi_ai
Revises: 0002_rls_policies
Create Date: 2026-06-20 14:56:22.423189
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003_core_pi_ai'
down_revision: str | None = '0002_rls_policies'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=32), nullable=True),
    sa.Column('best_time_to_contact', sa.String(length=64), nullable=True),
    sa.Column('case_type', sa.String(length=40), nullable=False),
    sa.Column('pipeline_status', sa.String(length=32), server_default=sa.text("'New Lead'"), nullable=False),
    sa.Column('qualification_status', sa.String(length=32), server_default=sa.text("'Needs Review'"), nullable=False),
    sa.Column('lead_temperature', sa.String(length=16), server_default=sa.text("'Low'"), nullable=False),
    sa.Column('lead_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('settlement_expected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retainer_status', sa.String(length=16), server_default=sa.text("'Not Ready'"), nullable=False),
    sa.Column('missing_documents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_follow_up_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'inbound_call'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("case_type IN ('Auto Accident', 'Truck Accident', 'Motorcycle Accident', 'Pedestrian Accident', 'Rideshare Accident', 'Slip and Fall', 'Dog Bite', 'Workplace Injury', 'Premises Liability', 'Wrongful Death', 'Other Personal Injury')", name='ck_leads_case_type'),
    sa.CheckConstraint("lead_temperature IN ('Hot', 'Warm', 'Low', 'Poor Fit')", name='ck_leads_temperature'),
    sa.CheckConstraint("pipeline_status IN ('New Lead', 'Intake Started', 'Intake Complete', 'Qualified', 'Needs Review', 'Docs Requested', 'Docs Received', 'Retainer Ready', 'Retainer Sent', 'Signed', 'Rejected', 'Closed')", name='ck_leads_pipeline_status'),
    sa.CheckConstraint("qualification_status IN ('Qualified', 'Possibly Qualified', 'Needs Review', 'Unqualified')", name='ck_leads_qualification_status'),
    sa.CheckConstraint("retainer_status IN ('Not Ready', 'Ready', 'Sent', 'Viewed', 'Signed', 'Declined', 'Expired')", name='ck_leads_retainer_status'),
    sa.CheckConstraint("source IN ('inbound_call', 'web', 'referral', 'other')", name='ck_leads_source'),
    sa.CheckConstraint('lead_score >= 0 AND lead_score <= 100', name='ck_leads_score_range'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_org_assigned', 'leads', ['organization_id', 'assigned_user_id'], unique=False)
    op.create_index('ix_leads_org_pipeline', 'leads', ['organization_id', 'pipeline_status'], unique=False)
    op.create_index('ix_leads_org_score', 'leads', ['organization_id', sa.text('lead_score DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_leads_org_updated', 'leads', ['organization_id', sa.text('updated_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('client_accounts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index('ix_client_accounts_organization_id', 'client_accounts', ['organization_id'], unique=False)
    op.create_table('damages',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('medical', 'future_medical', 'lost_wages', 'lost_earning_capacity', 'property', 'other')", name='ck_damages_category'),
    sa.CheckConstraint("source IS NULL OR source IN ('bill', 'statement', 'ai_estimate')", name='ck_damages_source'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_damages_lead_id', 'damages', ['lead_id'], unique=False)
    op.create_index('ix_damages_organization_id', 'damages', ['organization_id'], unique=False)
    op.create_table('incidents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('location_text', sa.String(length=512), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('police_report_available', sa.Boolean(), nullable=True),
    sa.Column('police_report_number', sa.String(length=64), nullable=True),
    sa.Column('fault_narrative', sa.Text(), nullable=True),
    sa.Column('comparative_negligence_pct', sa.Integer(), nullable=True),
    sa.Column('statute_of_limitations_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_lead_id', 'incidents', ['lead_id'], unique=False)
    op.create_index('ix_incidents_organization_id', 'incidents', ['organization_id'], unique=False)
    op.create_table('injuries',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('body_part', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=True),
    sa.Column('requires_surgery', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IS NULL OR severity IN ('Minor', 'Moderate', 'Severe', 'Permanent')", name='ck_injuries_severity'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_injuries_lead_id', 'injuries', ['lead_id'], unique=False)
    op.create_index('ix_injuries_organization_id', 'injuries', ['organization_id'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('party_role', sa.String(length=16), nullable=False),
    sa.Column('carrier_name', sa.String(length=255), nullable=True),
    sa.Column('policy_kind', sa.String(length=16), nullable=True),
    sa.Column('policy_number', sa.String(length=80), nullable=True),
    sa.Column('coverage_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('claim_number', sa.String(length=80), nullable=True),
    sa.Column('adjuster_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("party_role IN ('claimant', 'at_fault', 'other')", name='ck_insurance_policies_party_role'),
    sa.CheckConstraint("policy_kind IS NULL OR policy_kind IN ('Liability', 'UM', 'UIM', 'MedPay', 'Health', 'Other')", name='ck_insurance_policies_policy_kind'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insurance_policies_lead_id', 'insurance_policies', ['lead_id'], unique=False)
    op.create_index('ix_insurance_policies_organization_id', 'insurance_policies', ['organization_id'], unique=False)
    op.create_table('intake_transcripts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('voice_call_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='in_progress', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'complete', 'failed')", name='ck_intake_transcripts_status'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intake_transcripts_lead_id', 'intake_transcripts', ['lead_id'], unique=False)
    op.create_index('ix_intake_transcripts_organization_id', 'intake_transcripts', ['organization_id'], unique=False)
    op.create_table('lead_scores',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.String(length=16), nullable=True),
    sa.Column('qualification_status', sa.String(length=32), nullable=True),
    sa.Column('qualification_reason', sa.Text(), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), server_default='system', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("created_by_type IN ('user', 'system')", name='ck_lead_scores_created_by_type'),
    sa.CheckConstraint("qualification_status IS NULL OR qualification_status IN ('Qualified', 'Possibly Qualified', 'Needs Review', 'Unqualified')", name='ck_lead_scores_qualification_status'),
    sa.CheckConstraint("temperature IS NULL OR temperature IN ('Hot', 'Warm', 'Low', 'Poor Fit')", name='ck_lead_scores_temperature'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_lead_scores_range'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_scores_lead_created', 'lead_scores', ['lead_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_lead_scores_organization_id', 'lead_scores', ['organization_id'], unique=False)
    op.create_table('medical_treatments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('provider_type', sa.String(length=64), nullable=True),
    sa.Column('treatment_type', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_treatments_lead_id', 'medical_treatments', ['lead_id'], unique=False)
    op.create_index('ix_medical_treatments_organization_id', 'medical_treatments', ['organization_id'], unique=False)
    op.create_table('parties',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('at_fault', 'witness', 'passenger', 'other')", name='ck_parties_role'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parties_lead_id', 'parties', ['lead_id'], unique=False)
    op.create_index('ix_parties_organization_id', 'parties', ['organization_id'], unique=False)
    op.create_table('settlement_estimates',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('pain_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), server_default='system', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IS NULL OR confidence IN ('Low', 'Medium', 'High')", name='ck_settlement_estimates_confidence'),
    sa.CheckConstraint("created_by_type IN ('user', 'system')", name='ck_settlement_estimates_created_by_type'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_settlement_estimates_lead_created', 'settlement_estimates', ['lead_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_settlement_estimates_organization_id', 'settlement_estimates', ['organization_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("speaker IN ('caller', 'agent')", name='ck_transcript_segments_speaker'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['intake_transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcript_segments_organization_id', 'transcript_segments', ['organization_id'], unique=False)
    op.create_index('ix_transcript_segments_transcript_seq', 'transcript_segments', ['transcript_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcript_segments_transcript_seq', table_name='transcript_segments')
    op.drop_index('ix_transcript_segments_organization_id', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index('ix_settlement_estimates_organization_id', table_name='settlement_estimates')
    op.drop_index('ix_settlement_estimates_lead_created', table_name='settlement_estimates')
    op.drop_table('settlement_estimates')
    op.drop_index('ix_parties_organization_id', table_name='parties')
    op.drop_index('ix_parties_lead_id', table_name='parties')
    op.drop_table('parties')
    op.drop_index('ix_medical_treatments_organization_id', table_name='medical_treatments')
    op.drop_index('ix_medical_treatments_lead_id', table_name='medical_treatments')
    op.drop_table('medical_treatments')
    op.drop_index('ix_lead_scores_organization_id', table_name='lead_scores')
    op.drop_index('ix_lead_scores_lead_created', table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index('ix_intake_transcripts_organization_id', table_name='intake_transcripts')
    op.drop_index('ix_intake_transcripts_lead_id', table_name='intake_transcripts')
    op.drop_table('intake_transcripts')
    op.drop_index('ix_insurance_policies_organization_id', table_name='insurance_policies')
    op.drop_index('ix_insurance_policies_lead_id', table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index('ix_injuries_organization_id', table_name='injuries')
    op.drop_index('ix_injuries_lead_id', table_name='injuries')
    op.drop_table('injuries')
    op.drop_index('ix_incidents_organization_id', table_name='incidents')
    op.drop_index('ix_incidents_lead_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_damages_organization_id', table_name='damages')
    op.drop_index('ix_damages_lead_id', table_name='damages')
    op.drop_table('damages')
    op.drop_index('ix_client_accounts_organization_id', table_name='client_accounts')
    op.drop_table('client_accounts')
    op.drop_index('ix_leads_org_updated', table_name='leads', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_leads_org_score', table_name='leads', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_leads_org_pipeline', table_name='leads')
    op.drop_index('ix_leads_org_assigned', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
