"""phase 3 comms documents retainer workflow audit

Revision ID: 0005_comms_docs_workflow
Revises: 0004_phase2_rls
Create Date: 2026-06-20 15:08:14.106725
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005_comms_docs_workflow'
down_revision: str | None = '0004_phase2_rls'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('user', 'client', 'system')", name='ck_audit_logs_actor_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['organization_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_open', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('voice', 'sms', 'whatsapp', 'email')", name='ck_conversations_channel'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_lead_id', 'conversations', ['lead_id'], unique=False)
    op.create_index('ix_conversations_organization_id', 'conversations', ['organization_id'], unique=False)
    op.create_table('document_requests',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='Pending', nullable=False),
    sa.Column('requested_via', sa.String(length=16), nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('Police report', 'Accident photos', 'Injury photos', 'Medical records', 'Medical bills', 'Insurance correspondence', 'Driver''s license', 'Vehicle damage photos', 'Witness information', 'Employer wage loss documentation', 'Prior settlement offers')", name='ck_document_requests_document_type'),
    sa.CheckConstraint("requested_via IS NULL OR requested_via IN ('voice', 'sms', 'whatsapp', 'email')", name='ck_document_requests_requested_via'),
    sa.CheckConstraint("status IN ('Pending', 'Sent', 'Partially Received', 'Received', 'Waived')", name='ck_document_requests_status'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_requests_lead_id', 'document_requests', ['lead_id'], unique=False)
    op.create_index('ix_document_requests_organization_id', 'document_requests', ['organization_id'], unique=False)
    op.create_table('internal_notes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_internal_notes_lead_id', 'internal_notes', ['lead_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_internal_notes_organization_id', 'internal_notes', ['organization_id'], unique=False)
    op.create_table('retainers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='Not Ready', nullable=False),
    sa.Column('template_id', sa.String(length=80), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('esign_provider', sa.String(length=40), nullable=True),
    sa.Column('esign_envelope_id', sa.String(length=128), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Not Ready', 'Ready', 'Sent', 'Viewed', 'Signed', 'Declined', 'Expired')", name='ck_retainers_status'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index('ix_retainers_organization_id', 'retainers', ['organization_id'], unique=False)
    op.create_table('tasks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('created_by', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("created_by IN ('user', 'system')", name='ck_tasks_created_by'),
    sa.CheckConstraint("status IN ('open', 'done', 'snoozed', 'cancelled')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_lead_id', 'tasks', ['lead_id'], unique=False)
    op.create_index('ix_tasks_org_assigned', 'tasks', ['organization_id', 'assigned_user_id'], unique=False)
    op.create_index('ix_tasks_organization_id', 'tasks', ['organization_id'], unique=False)
    op.create_table('voice_calls',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('from_e164', sa.String(length=20), nullable=True),
    sa.Column('to_e164', sa.String(length=20), nullable=True),
    sa.Column('provider_sid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name='ck_voice_calls_direction'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_sid')
    )
    op.create_index('ix_voice_calls_lead_id', 'voice_calls', ['lead_id'], unique=False)
    op.create_index('ix_voice_calls_organization_id', 'voice_calls', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('document_request_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=16), nullable=True),
    sa.Column('scan_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("scan_status IN ('pending', 'clean', 'infected')", name='ck_documents_scan_status'),
    sa.CheckConstraint("uploaded_by IS NULL OR uploaded_by IN ('client', 'user', 'agent')", name='ck_documents_uploaded_by'),
    sa.ForeignKeyConstraint(['document_request_id'], ['document_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_lead_id', 'documents', ['lead_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_documents_organization_id', 'documents', ['organization_id'], unique=False)
    op.create_index('ix_documents_request_id', 'documents', ['document_request_id'], unique=False)
    op.create_table('messages',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('purpose', sa.String(length=16), server_default='general', nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('voice', 'sms', 'whatsapp', 'email')", name='ck_messages_channel'),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name='ck_messages_direction'),
    sa.CheckConstraint("purpose IN ('intake', 'follow_up', 'doc_request', 'retainer', 'general')", name='ck_messages_purpose'),
    sa.CheckConstraint("status IN ('queued', 'sent', 'delivered', 'failed', 'received')", name='ck_messages_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_lead_id', 'messages', ['lead_id'], unique=False)
    op.create_index('ix_messages_organization_id', 'messages', ['organization_id'], unique=False)
    op.create_table('signature_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('retainer_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor IS NULL OR actor IN ('client', 'system')", name='ck_signature_events_actor'),
    sa.CheckConstraint("event IN ('sent', 'viewed', 'signed', 'declined', 'expired')", name='ck_signature_events_event'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retainer_id'], ['retainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signature_events_lead_id', 'signature_events', ['lead_id'], unique=False)
    op.create_index('ix_signature_events_organization_id', 'signature_events', ['organization_id'], unique=False)
    op.create_index('ix_signature_events_retainer_id', 'signature_events', ['retainer_id'], unique=False)
    op.create_foreign_key('fk_intake_transcripts_voice_call_id', 'intake_transcripts', 'voice_calls', ['voice_call_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_intake_transcripts_voice_call_id', 'intake_transcripts', type_='foreignkey')
    op.drop_index('ix_signature_events_retainer_id', table_name='signature_events')
    op.drop_index('ix_signature_events_organization_id', table_name='signature_events')
    op.drop_index('ix_signature_events_lead_id', table_name='signature_events')
    op.drop_table('signature_events')
    op.drop_index('ix_messages_organization_id', table_name='messages')
    op.drop_index('ix_messages_lead_id', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_documents_request_id', table_name='documents')
    op.drop_index('ix_documents_organization_id', table_name='documents')
    op.drop_index('ix_documents_lead_id', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('documents')
    op.drop_index('ix_voice_calls_organization_id', table_name='voice_calls')
    op.drop_index('ix_voice_calls_lead_id', table_name='voice_calls')
    op.drop_table('voice_calls')
    op.drop_index('ix_tasks_organization_id', table_name='tasks')
    op.drop_index('ix_tasks_org_assigned', table_name='tasks')
    op.drop_index('ix_tasks_lead_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_retainers_organization_id', table_name='retainers')
    op.drop_table('retainers')
    op.drop_index('ix_internal_notes_organization_id', table_name='internal_notes')
    op.drop_index('ix_internal_notes_lead_id', table_name='internal_notes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('internal_notes')
    op.drop_index('ix_document_requests_organization_id', table_name='document_requests')
    op.drop_index('ix_document_requests_lead_id', table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_index('ix_conversations_organization_id', table_name='conversations')
    op.drop_index('ix_conversations_lead_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
