"""phase 4 ai memory and event backbone

Revision ID: 0007_ai_memory_events
Revises: 0006_phase3_rls
Create Date: 2026-06-20 15:22:52.329496
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.halfvec

# revision identifiers, used by Alembic.
revision: str = '0007_ai_memory_events'
down_revision: str | None = '0006_phase3_rls'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before the knowledge_chunks halfvec column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='received', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('received', 'processed', 'ignored')", name='ck_webhook_events_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index('ix_webhook_events_provider', 'webhook_events', ['provider'], unique=False)
    op.create_table('outbox_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'published', 'failed')", name='ck_outbox_events_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_events_due', 'outbox_events', ['available_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_outbox_events_organization_id', 'outbox_events', ['organization_id'], unique=False)
    op.create_table('agent_threads',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('thread_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_key')
    )
    op.create_index('ix_agent_threads_lead_id', 'agent_threads', ['lead_id'], unique=False)
    op.create_index('ix_agent_threads_organization_id', 'agent_threads', ['organization_id'], unique=False)
    op.create_table('kg_nodes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node_type IN ('person', 'injury', 'provider', 'insurer', 'incident', 'fact', 'document')", name='ck_kg_nodes_node_type'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kg_nodes_lead_id', 'kg_nodes', ['lead_id'], unique=False)
    op.create_index('ix_kg_nodes_organization_id', 'kg_nodes', ['organization_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('transcript', 'document', 'note', 'settlement', 'medical', 'message', 'incident')", name='ck_knowledge_chunks_source_type'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunks_org_lead', 'knowledge_chunks', ['organization_id', 'lead_id'], unique=False)
    op.create_index('ix_knowledge_chunks_source', 'knowledge_chunks', ['source_type', 'source_id'], unique=False)
    # Vector ANN (cosine) + keyword (BM25-style) indexes for hybrid retrieval.
    # Also declared on the KnowledgeChunk model so `alembic check` watches them.
    op.create_index(
        'ix_knowledge_chunks_embedding_hnsw',
        'knowledge_chunks',
        ['embedding'],
        postgresql_using='hnsw',
        postgresql_ops={'embedding': 'halfvec_cosine_ops'},
    )
    op.create_index(
        'ix_knowledge_chunks_content_tsv_gin',
        'knowledge_chunks',
        ['content_tsv'],
        postgresql_using='gin',
    )
    op.create_table('agent_checkpoints',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('agent_thread_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=128), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_checkpoint_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_thread_id'], ['agent_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_checkpoints_lead_id', 'agent_checkpoints', ['lead_id'], unique=False)
    op.create_index('ix_agent_checkpoints_organization_id', 'agent_checkpoints', ['organization_id'], unique=False)
    op.create_index('ix_agent_checkpoints_thread_id', 'agent_checkpoints', ['agent_thread_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('agent_thread_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('tool_call', 'tool_result', 'decision', 'error')", name='ck_agent_events_event_type'),
    sa.ForeignKeyConstraint(['agent_thread_id'], ['agent_threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_events_lead_id', 'agent_events', ['lead_id'], unique=False)
    op.create_index('ix_agent_events_organization_id', 'agent_events', ['organization_id'], unique=False)
    op.create_index('ix_agent_events_thread_id', 'agent_events', ['agent_thread_id'], unique=False)
    op.create_table('kg_edges',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('subject_node_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('object_node_id', sa.UUID(), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_node_id'], ['kg_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_node_id'], ['kg_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kg_edges_lead_id', 'kg_edges', ['lead_id'], unique=False)
    op.create_index('ix_kg_edges_object_node_id', 'kg_edges', ['object_node_id'], unique=False)
    op.create_index('ix_kg_edges_organization_id', 'kg_edges', ['organization_id'], unique=False)
    op.create_index('ix_kg_edges_subject_node_id', 'kg_edges', ['subject_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kg_edges_subject_node_id', table_name='kg_edges')
    op.drop_index('ix_kg_edges_organization_id', table_name='kg_edges')
    op.drop_index('ix_kg_edges_object_node_id', table_name='kg_edges')
    op.drop_index('ix_kg_edges_lead_id', table_name='kg_edges')
    op.drop_table('kg_edges')
    op.drop_index('ix_agent_events_thread_id', table_name='agent_events')
    op.drop_index('ix_agent_events_organization_id', table_name='agent_events')
    op.drop_index('ix_agent_events_lead_id', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index('ix_agent_checkpoints_thread_id', table_name='agent_checkpoints')
    op.drop_index('ix_agent_checkpoints_organization_id', table_name='agent_checkpoints')
    op.drop_index('ix_agent_checkpoints_lead_id', table_name='agent_checkpoints')
    op.drop_table('agent_checkpoints')
    op.drop_index('ix_knowledge_chunks_source', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_org_lead', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_kg_nodes_organization_id', table_name='kg_nodes')
    op.drop_index('ix_kg_nodes_lead_id', table_name='kg_nodes')
    op.drop_table('kg_nodes')
    op.drop_index('ix_agent_threads_organization_id', table_name='agent_threads')
    op.drop_index('ix_agent_threads_lead_id', table_name='agent_threads')
    op.drop_table('agent_threads')
    op.drop_index('ix_outbox_events_organization_id', table_name='outbox_events')
    op.drop_index('ix_outbox_events_due', table_name='outbox_events', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('outbox_events')
    op.drop_index('ix_webhook_events_provider', table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
