"""auth lookup phone and login indexes

Revision ID: 0009_auth_lookups
Revises: 0008_phase4_rls
Create Date: 2026-06-20 16:04:17.911679
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009_auth_lookups'
down_revision: str | None = '0008_phase4_rls'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_client_accounts_org_email', 'client_accounts', ['organization_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_client_accounts_org_phone', 'client_accounts', ['organization_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.create_index('uq_users_phone', 'users', ['phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_phone', table_name='users', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_column('users', 'phone')
    op.drop_index('uq_client_accounts_org_phone', table_name='client_accounts', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('uq_client_accounts_org_email', table_name='client_accounts', postgresql_where=sa.text('email IS NOT NULL'))
    # ### end Alembic commands ###
