"""users phone per-org unique

Revision ID: 0010_users_phone_per_org
Revises: 0009_auth_lookups
Create Date: 2026-06-20 16:18:42.129797
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010_users_phone_per_org'
down_revision: str | None = '0009_auth_lookups'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_phone', table_name='users', postgresql_where='(phone IS NOT NULL)')
    op.create_index('uq_users_org_phone', 'users', ['organization_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_org_phone', table_name='users', postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_index('uq_users_phone', 'users', ['phone'], unique=True, postgresql_where='(phone IS NOT NULL)')
    # ### end Alembic commands ###
